### PR TITLE
Update Broadworks OCIP library with latest interface version

### PR DESCRIPTION
**Pull request by ewurch**
This is the placeholder Pull Request for the update of the broadworks_ocip library with last version of BroadWorks

### CODE REVIEW

**Comment by ewurch** [comment]
@staticdev

**Comment by staticdev** [comment]
@nigelm I contacted @ewurch (we work together) and we are not sure if it is possible to limit the change to only UserSequentialRing, but changes are based on the new schema. Could you please do an initial look and share tour thoughts? Maybe point out if you think something is missing? As a first cobtribution, it is not really easy to navigate all files.

**Comment by nigelm** [comment]
> @nigelm I contacted @ewurch (we work together) and we are not sure if it is possible to limit the change to only UserSequentialRing, but changes are based on the new schema. Could you please do an initial look and share your thoughts? Maybe point out if you think something is missing? As a first cobtribution, it is not really easy to navigate all files.

The `process_schema.py` started as a bit of a hack and has evolved to deep dark magic... sorry, you are right it is difficult to understand that (also for me coming back to it after a year not working on it).  I must document it better.

I would much rather put the whole schema update out, rather than trying to limit to one use case.

The change looks good with one exception - which was flagged up by the changes I have made to the  pre-commit config, and shows up a bug/assumption I made in `process_schema.py` - that schema items with names that match '...Request` are `OciRequests` - because there is an exception `SearchCriteriaDeviceManagementEventRequest`.  That one should be a Type rather than a Request.   Interestingly I rewrote things to use the Schema extension base class to divide things up instead, and found that  `CallCenterAgentAvailability` and `CallCenterAgentSettings` are both defined as Requests in the schemas but appear to me to be types since they can be embedded in other requests.

So can I suggest:

- rebase on top of current master to get the pre-commit config changes (ruff is much faster anyhow for these huge files)
- apply the change in commit 3aa41dd2c627323a4cce59788c8aa9ea6c682ef0
- regenerate the derived files `make code; git add .; pre-commit run`

Alternatively I can go with the branch I was experimenting on this morning - `update_r25_schema` that does these bits anyhow, but does scrub credit from you in the commit list - I will certainly make sure I do update the README appropriately.

**Comment by ewurch** [comment]
Dear @nigelm, thanks a lot for your answer.

> I would much rather put the whole schema update out, rather than trying to limit to one use case.

From what I've seem, I also prefer this approach. Otherwise we would have to deal with standalone changes in the OCISchemaDeprecated.xsd and OCISchemaDataTypes.xsd files. 

> The change looks good with one exception - which was flagged up by the changes I have made to the pre-commit config, and shows up a bug/assumption I made in `process_schema.py` - that schema items with names that match '...Request`are`OciRequests`- because there is an exception`SearchCriteriaDeviceManagementEventRequest`. That one should be a Type rather than a Request. Interestingly I rewrote things to use the Schema extension base class to divide things up instead, and found that `CallCenterAgentAvailability`and`CallCenterAgentSettings` are both defined as Requests in the schemas but appear to me to be types since they can be embedded in other requests.

I really appreciate that you took the time to take a look at the PR. One thing that I notice while testing, is that the outdated requests doesn't have the `Replaced by "NewRequestVersionXYZ"` automatically inserted into their docstrings. 

Is that something that I should proactively do?

**Comment by nigelm** [comment]
> I really appreciate that you took the time to take a look at the PR. One thing that I notice while testing, is that the outdated requests doesn't have the `Replaced by "NewRequestVersionXYZ"` automatically inserted into their docstrings.

I don't currently change the docstrings from the info in the schema at all.  Adding that additional info would be really useful.

Having looked at the code in `process_schema.py` (what was I thinking - it was basically a quick hack that grew), I am currently itching to replace it with something thats much better structured.

**Pull request merged**
